### ISSUE TITLE
Implementar sistema de login e cadastro RF-011

### ISSUE THREAD

**Issue by mfernandasilva** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t5-eixo_2_grupo_5#28]

**Comment by EddyMoura** [comment]
A aplicação deve fornecer um mecanismo de login e registro para as empresas e os profissionais. O login e o registro devem ser separados para cada tipo de usuário (empresas e profissionais) permitindo que eles acessem funcionalidades específicas. As empresas devem ter a opção de se registrar na plataforma, fornecendo informação como nome da empresa, endereço de email, número de telefone, CNPJ, senha e confirmar senha. Os profissionais devem ter a opção de se registrar na plataforma fornecendo informações como nome completo, endereço de email, senha e confirmar senha. Após o registro, as empresas e os profissionais devem ter a opção de fazer login na plataforma usando suas credenciais (por exemplo, e-mail e senha).

**Comment by EddyMoura** [comment]
Login e Cadastro Profissional: https://drive.google.com/file/d/1W9TJC55pgyzbAA6SwxiaMBQkdN7LQway/view?usp=share_link
Login e Cadastro Empresa: https://drive.google.com/file/d/1a4Flp9umghbaiHtGbvR81xU-PDa1m6x4/view?usp=share_link
